### PR TITLE
Including nb2workflow metadata

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
I missed to push two commits from #50, my bad.

**Comment by burnout87** [comment]
This needs to be merged

**Comment by volodymyrss** [comment]
> This needs to be merged

This needs to be reviewed and we need to confirm it does what we want, right? 
You can show today what is the status!

**Comment by volodymyrss** [comment]
is it blocking some other development?

**Comment by volodymyrss** [comment]
> > > This needs to be merged
> > 
> > 
> > This needs to be reviewed and we need to confirm it does what we want, right? You can show today what is the status!
> 
> This is kind a continuation of #50 , I just had to re-open it since I had forgotten to push two changes that I have already shown during the last smartsky meeting. The next development will be #56

Alright, could you please explain it when you make a request? It's not likely anything needs to be merged without some clarity and discussion.

**Review by volodymyrss — APPROVED** [review]
the changes are minor

**Pull request merged**
