### PR TITLE
Including nb2workflow metadata

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
An annotation is created and added to the graph at the end of a `renku run` command, within the `activity_annotations` hook.

<details> 
  <summary>These are the annotations added to the graph : </summary>

``` ttl
...
<http://odahub.io/workflows#out_e3eb519e> a oda:workflow ;
    oda:expects <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#DEC>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#RA>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#T1>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#T2>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#a>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#dT>,
        <http://odahub.io/workflows/out_e3eb519e/parameter_bindings#src_name> ;
    oda:location "git@renkulab.io:astronomy/mmoda/fermi.git#ef8f8c5" .

...

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#DEC> a oda:PointOfInterestDEC .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#RA> a oda:PointOfInterestRA .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#T1> a oda:StartTime .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#T2> a oda:EndTime .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#a> a xsd:int .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#dT> a xsd:int .

<http://odahub.io/workflows/out_e3eb519e/parameter_bindings#src_name> a oda:AstrophysicalObject .
...
```

</details>

**Comment by burnout87** [comment]
Ok I can extract the metadata via `nb2workflow`, but I am a bit lost on how to best include those within the graph.

Perhaps we should discuss it together, looking directly at the graph...

**Comment by burnout87** [comment]
by using the input notebook `fermi_lc.ipynb` for this example, I now get less annotation, as it seems that one parameter binding less is found by the `nb2rdf`.

<details> 
  <summary>These are the annotations added to the graph : </summary>

``` ttl
...
<http://odahub.io/workflows#fermi_lc_5bb8e0d5> a oda:workflow ;
    oda:expects <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#DEC>,
        <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#RA>,
        <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#T1>,
        <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#T2>,
        <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#dT>,
        <http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#src_name> ;
    oda:location "git@renkulab.io:astronomy/mmoda/fermi.git#b08df21" .

...

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#DEC> a oda:PointOfInterestDEC .

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#RA> a oda:PointOfInterestRA .

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#T1> a oda:StartTime .

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#T2> a oda:EndTime .

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#dT> a xsd:int .

<http://odahub.io/workflows/fermi_lc_5bb8e0d5/parameter_bindings#src_name> a oda:AstrophysicalObject .
...
```

</details>

**Comment by burnout87** [comment]
I attached the workflow annotations to the activity so to be consistent with the approach used to build the graph, where we for each activity we extract the entities for the inputs and outputs. In this way, I extract the various parameter-bindings starting from the entityInput (`fermi_lc.ipynb` in the example).

image

**Comment by burnout87** [comment]
Another, partial, result:

image

**Comment by volodymyrss** [comment]
Looks interesting but since review is not requested I suppose it's not ready? Anyway we can discuss today.

**Comment by burnout87** [comment]
As discussed, now the type assigned to each parameter_binding is is inserted in the graph

image

**Comment by burnout87** [comment]
Color also updated

image

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
