### PR TITLE
Button show hidden nodes

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by volodymyrss** [comment]
oh, to review effectively, could you make a renkulab repository with an example, and put here a link to start a session?

**Comment by burnout87** [comment]
https://renkulab.io/projects/gabriele.barni/grb-detection/sessions/new

does this work? using the latest commit on the master branch....

**Comment by volodymyrss** [comment]
image

**Comment by burnout87** [comment]
> image

You have to use the latest commit, I see the docker image is currently available

**Comment by volodymyrss** [comment]
> > image
> 
> You have to use the latest commit, I see the docker image is currently available

which commit? maybe I am not seeing the same commits?
Could you please make a url with the commit which works? You know how to, like in mmoda urls.

**Comment by burnout87** [comment]
> Could you please make a url with the commit which works? You know how to, like in mmoda urls.

Does this work? https://renkulab.io/projects/gabriele.barni/grb-detection/sessions/new?autostart=1&commit=e7d33243c547410cb017c483d141397cf5a8a454&branch=master

Otherwise I probably have to change something in the permissions

**Comment by volodymyrss** [comment]
hide button works now, but "show hidden nodes" button is now gone

image

**Comment by burnout87** [comment]
I wonder, are you using the branch of this PR? Are you using the link I generated to start the session?

In my repo, I specified it. So the latest image should have it...

**Comment by volodymyrss** [comment]
> I wonder, are you using the branch of this PR? Are you using the link I generated to start the session?
> 
> In my repo, I specified it. So the latest image should have it...

I am using the link you specified. By clicking on this link I end up in a session which leads to that screenshot. Do you see different?

**Comment by burnout87** [comment]
> > I wonder, are you using the branch of this PR? Are you using the link I generated to start the session?
> > In my repo, I specified it. So the latest image should have it...
> 
> I am using the link you specified. By clicking on this link I end up in a session which leads to that screenshot. Do you see different?

I fear the image does not have that version of the plugin...I notecoed that sometimes, and I never understood why. 

That is why, once I start the session, I have to re-run the installation of the requirements

**Comment by volodymyrss** [comment]
Ok, I find the commit and can start  a session with [this link](https://renkulab.io/projects/gabriele.barni/grb-detection/sessions/new?autostart=1&commit=98c8fb08470b5fdb9fb9a61de7f0ae9609d0303d&branch=master) but there is some problem with hiding, see #46 - it does not hide for me

> > > I wonder, are you using the branch of this PR? Are you using the link I generated to start the session?
> > > In my repo, I specified it. So the latest image should have it...
> > 
> > 
> > I am using the link you specified. By clicking on this link I end up in a session which leads to that screenshot. Do you see different?
> 
> I fear the image does not have that version of the plugin...I notecoed that sometimes, and I never understood why.
> 
> That is why, once I start the session, I have to re-run the installation of the requirements

Could you make the commit so that there will be a URL which fully works? Also with migration.
It's also important for us to experience renku more now.

**Comment by burnout87** [comment]
> Could you make the commit so that there will be a URL which fully works? Also with migration. It's also important for us to experience renku more now.

Does this work now? 

https://renkulab.io/projects/gabriele.barni/grb-detection/sessions/new?autostart=1&commit=7a8d5859f31129837a6e4c1ead9cff9f9c2cb65c&branch=master

I directly make the installation from the Dockerfile

**Comment by volodymyrss** [comment]
yes, thanks!

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
